"""Repository abstractions for VisualAI persistence (Phase 12C).

Defines the contract for domain entity repositories, allowing pluggable
backends (File-based local JSON vs. Remote Supabase PostgreSQL).
"""

from typing import Any, Protocol
from pathlib import Path
from ..schemas import ContentUnit, KnowledgeGraph, SourceRecord
from ..assessment.schemas import AssessmentSession, StudentLearningProfile, VideoTargetMatrix


class SourceRepository(Protocol):
    """Abstract persistence for Step 1 Sources, ContentUnits, and KnowledgeGraphs."""

    def get_source(self, source_id: str) -> SourceRecord | None: ...
    def save_source(self, record: SourceRecord) -> None: ...
    def list_sources(self) -> list[SourceRecord]: ...
    def get_content_units(self, source_id: str) -> list[ContentUnit]: ...
    def save_content_units(self, source_id: str, units: list[ContentUnit]) -> None: ...
    def get_knowledge_graph(self, source_id: str) -> KnowledgeGraph | None: ...
    def save_knowledge_graph(self, source_id: str, kg: KnowledgeGraph) -> None: ...


class AssessmentRepository(Protocol):
    """Abstract persistence for Step 2 Assessment Sessions and Submissions."""

    def get_session(self, session_id: str) -> AssessmentSession | None: ...
    def save_session(self, session: AssessmentSession) -> None: ...


class LearningProfileRepository(Protocol):
    """Abstract persistence for Student Learning Profiles and Video Targets."""

    def get_profile(self, student_id: str, source_id: str) -> StudentLearningProfile | None: ...
    def save_profile(self, profile: StudentLearningProfile) -> None: ...
    def get_video_matrix(self, student_id: str, source_id: str) -> VideoTargetMatrix | None: ...
    def save_video_matrix(self, matrix: VideoTargetMatrix) -> None: ...
