'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const ui=require('../app/static/practice.js');
class Element {constructor(tag='div'){this.tag=tag;this.children=[];this.textContent='';this.hidden=false;this.disabled=false;this.events={};}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}addEventListener(name,fn){this.events[name]=fn;}set innerHTML(value){throw new Error('Unsafe HTML');}}
class Document {constructor(){this.ids=Object.fromEntries(['practice-tab','practice-panel','practice-status','practice-content','mastery-content','start-practice','refresh-practice'].map(id=>[id,new Element()]));}getElementById(id){return this.ids[id];}createElement(tag){return new Element(tag);}}
const question={question_id:'q',concept_id:'c',concept_name:'Cell',stem:'Visible question?',options:[{index:0,text:'One'},{index:1,text:'Two'}]};
const response=value=>({ok:true,status:200,json:async()=>value});
const session={session_id:'owned',state:'ACTIVE'};
function all(el){return [el,...el.children.flatMap(all)];}
test('SafeQuestion rejects hidden answers at any depth',()=>{ui.assertSafeQuestions([question]);for(const key of ['correct_index','correct_answer','answer_key','grading_rationale','explanation','rationale','is_correct'])assert.throws(()=>ui.assertSafeQuestions([{...question,metadata:{[key]:'secret'}}]));});
test('generation is session-scoped, bounded and idempotent while pending',async()=>{const doc=new Document();let finish;const calls=[];const controller=ui.createController(doc,(...args)=>{calls.push(args);return new Promise(resolve=>finish=resolve);});controller.setSession(session);const work=controller.start();await controller.start();assert.equal(calls.length,1);assert.equal(calls[0][0],'/learning-sessions/owned/assessment');const body=JSON.parse(calls[0][1].body);assert.equal(body.question_count,3);assert.deepEqual(Object.keys(body).sort(),['question_count','request_id']);finish(response({session_id:'assessment',questions:[question]}));await work;assert(all(doc.ids['practice-content']).some(e=>e.textContent===question.stem));});
test('submission persists then reads result and finalizes canonical mastery',async()=>{const doc=new Document();const calls=[];const controller=ui.createController(doc,async(url,options)=>{calls.push(url);if(url.endsWith('/assessment'))return response({session_id:'a',questions:[question]});if(url.endsWith('/result'))return response({overall_score:0,concept_results:[{concept_id:'c',correct:0,attempted:1}]});if(url.endsWith('/result'))return response({overall_score:100,concept_results:[]});if(url.endsWith('/mastery'))return response({mastery:[{concept_id:'c',mastery_state:'NEEDS_SUPPORT'}],remediation:[],reassessment_job_ids:[]});return response({});});controller.setSession(session);await controller.start();all(doc.ids['practice-content']).find(e=>e.tag==='input').events.change();await controller.submit();assert.deepEqual(calls.slice(1),['/learning-sessions/owned/assessments/a/submit','/learning-sessions/owned/assessments/a/result','/learning-sessions/owned/mastery/finalize','/learning-sessions/owned/mastery']);assert(all(doc.ids['mastery-content']).some(e=>String(e.textContent).includes('NEEDS_SUPPORT')));});
test('late generation cannot overwrite another session or leak errors',async()=>{const doc=new Document();let finish;const controller=ui.createController(doc,()=>new Promise(resolve=>finish=resolve));controller.setSession(session);const pending=controller.start();controller.setSession({session_id:'new',state:'ACTIVE'});finish(response({session_id:'old',questions:[question]}));await pending;assert.equal(doc.ids['practice-content'].children.length,0);assert(!doc.ids['practice-status'].textContent.includes('Generating'));});

test('late submission cannot finalize or read another session',async()=>{const doc=new Document();let finish;const calls=[];const controller=ui.createController(doc,async(url)=>{calls.push(url);if(url.endsWith('/assessment'))return response({session_id:'a',questions:[question]});return new Promise(resolve=>finish=resolve);});controller.setSession(session);await controller.start();all(doc.ids['practice-content']).find(e=>e.tag==='input').events.change();const pending=controller.submit();controller.setSession({session_id:'new',state:'ACTIVE'});finish(response({}));await pending;assert.equal(calls.length,2);assert(calls.every(url=>url.startsWith('/learning-sessions/owned/')));});

test('refresh restores only an owned SafeQuestion assessment from canonical API',async()=>{const doc=new Document();const calls=[];const saved=new Map([['visualai-practice:owned','existing']]);const storage={getItem:key=>saved.get(key)||null,setItem:(key,value)=>saved.set(key,value)};const controller=ui.createController(doc,async(url)=>{calls.push(url);if(url.endsWith('/assessments/existing'))return response({session_id:'existing',status:'READY',questions:[question]});return response({mastery:[],remediation:[],reassessment_job_ids:[]});},storage);controller.setSession(session);await controller.refresh();assert.equal(calls[0],'/learning-sessions/owned/assessments/existing');assert(all(doc.ids['practice-content']).some(e=>e.textContent===question.stem));});
test('refresh retries persisted submitted assessment finalization without generation',async()=>{const doc=new Document();const calls=[];const storage={getItem:()=> 'existing',setItem:()=>{}};const controller=ui.createController(doc,async(url)=>{calls.push(url);if(url.endsWith('/assessments/existing'))return response({session_id:'existing',status:'SUBMITTED',questions:[question]});if(url.endsWith('/result'))return response({overall_score:100,concept_results:[]});if(url.endsWith('/mastery'))return response({mastery:[],remediation:[],reassessment_job_ids:[]});return response({});},storage);controller.setSession(session);await controller.refresh();assert.deepEqual(calls,['/learning-sessions/owned/assessments/existing','/learning-sessions/owned/assessments/existing/result','/learning-sessions/owned/mastery/finalize','/learning-sessions/owned/mastery']);});


test('submitted result survives refresh and canonical concept names remain visible',async()=>{const doc=new Document();const store={getItem:()=> 'a',setItem:()=>{}};const calls=[];const controller=ui.createController(doc,async(url)=>{calls.push(url);if(url.endsWith('/assessments/a'))return response({session_id:'a',status:'SUBMITTED',questions:[{...question,concept_name:'Selected concept'}]});if(url.endsWith('/result'))return response({overall_score:100,concept_results:[{concept_id:'c',correct:1,attempted:1}]});if(url.endsWith('/mastery'))return response({mastery:[{concept_id:'c',mastery_state:'REASSESSING'}],remediation:[]});return response({});},store);controller.setSession(session,[{concept_id:'c',name:'Actual grounded component'}]);await controller.refresh();assert(all(doc.ids['practice-content']).some(e=>e.textContent==='Score: 100%'));assert(all(doc.ids['mastery-content']).some(e=>e.textContent.includes('Actual grounded component')));assert(calls.includes('/learning-sessions/owned/assessments/a/result'));});
