"""Pydantic schemas for Step 3 Video Intelligence and Deterministic Manim Pipeline.

Defines typed contracts for:
- Scene types and elemental animations
- VideoPlan and NarrationScript
- VideoJob state and persistent VideoArtifact metadata
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class SceneType(str, Enum):
    """Allowed deterministic scene types — strictly constrained to prevent arbitrary code."""
    TITLE = "TITLE"
    TEXT = "TEXT"
    EQUATION = "EQUATION"
    DIAGRAM = "DIAGRAM"
    ARROW = "ARROW"
    HIGHLIGHT = "HIGHLIGHT"
    TRANSFORM = "TRANSFORM"
    EXAMPLE = "EXAMPLE"
    SUMMARY = "SUMMARY"


class VideoJobStatus(str, Enum):
    """Observable progression states for asynchronous video jobs."""
    QUEUED = "QUEUED"
    PLANNING = "PLANNING"
    RENDERING = "RENDERING"
    GENERATING_AUDIO = "GENERATING_AUDIO"
    ALIGNING = "ALIGNING"
    COMPOSITING = "COMPOSITING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class SceneElement(BaseModel):
    """Declarative visual element inside a scene."""
    element_type: SceneType = SceneType.TEXT
    text: str | None = None
    equation: str | None = None
    label: str | None = None
    color: str | None = None
    position: str | None = None  # e.g., "top", "center", "bottom"


class ScenePlan(BaseModel):
    """Structured plan for a single deterministic animation scene."""
    scene_index: int = 0
    scene_type: SceneType = SceneType.TEXT
    duration_seconds: float = Field(default=5.0, ge=1.0, le=60.0)
    title: str | None = None
    subtitle: str | None = None
    text: str | None = None
    equation: str | None = None
    label: str | None = None
    diagram_type: str | None = None  # e.g., "force_box", "coordinate_axis"
    object_label: str | None = None
    force_label: str | None = None
    acceleration_label: str | None = None
    mass_value: float | None = None
    force_value: float | None = None
    acceleration_value: float | None = None
    summary_points: list[str] = Field(default_factory=list)
    elements: list[SceneElement] = Field(default_factory=list)


class NarrationSegment(BaseModel):
    """Voiceover text corresponding to a specific scene index."""
    segment_id: str = Field(default_factory=lambda: f"narr_{uuid4().hex[:8]}")
    scene_index: int
    text: str
    target_seconds: float = 5.0


class NarrationScript(BaseModel):
    """Complete narration script for TTS generation and alignment."""
    concept_id: str
    total_target_seconds: float
    segments: list[NarrationSegment] = Field(default_factory=list)
    full_text: str = ""


class VideoPlan(BaseModel):
    """Complete blueprint generated by LLM reasoning for deterministic rendering."""
    plan_id: str = Field(default_factory=lambda: f"PLAN_{uuid4().hex[:10].upper()}")
    student_id: str = "STU_DEFAULT"
    source_id: str = "SRC_DEFAULT"
    concept_id: str
    concept_name: str
    duration_seconds: int = 45  # 30, 45, or 60 per specification
    difficulty: str = "intermediate"
    learning_objective: str = ""
    key_points: list[str] = Field(default_factory=list)
    scenes: list[ScenePlan] = Field(default_factory=list)
    narration: list[NarrationSegment] = Field(default_factory=list)
    provenance_chunks: list[str] = Field(default_factory=list)
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


class VideoArtifact(BaseModel):
    """Persistent record of a rendered and composited remedial video."""
    job_id: str
    student_id: str
    source_id: str
    concept_id: str
    concept_name: str
    duration_seconds: float = 0.0
    status: VideoJobStatus = VideoJobStatus.QUEUED
    stage: str = "QUEUED"
    progress: int = 0
    video_path: str | None = None
    audio_path: str | None = None
    subtitle_path: str | None = None
    provenance_chunks: list[str] = Field(default_factory=list)
    source_content_ids: list[str] = Field(default_factory=list)
    page_start: int | None = None
    page_end: int | None = None
    error: str | None = None
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    completed_at: str | None = None
